### ISSUE TITLE
Input 'Time' won't work with timeslice queries. Need better workaround.

### ISSUE THREAD

**Issue by markstur** [IBM/watson-discovery-food-reviews#5]
Looks like we need the JSON to either use a number timestamp or a quoted string formatted date, but csvtojson gave us a quoted timestamp.  This is currently fixed in the lib when we addDoc, but we probably should fix it in JSON so files can be added using the Disco UI (and remove the current tweak).

**Comment by markstur** [comment]
Note:  It'd be easy to fix the 26 files, but there are actually 568,454 of them so will revisit when looking into making a better selection of reviews available.

**Comment by stevemart** [comment]
@markstur I think you partially addressed this in #6 but it's not fully resolved.

**Comment by markstur** [comment]
Fixed in #6  
Steve, did you say "not fully resolved" because I didn't close the issue yet, or are you still seeing a problem?

**Comment by stevemart** [comment]
the latter
