### ISSUE TITLE
Help with breaking the reviews file into json

### ISSUE THREAD

**Issue by Tkprudent** [IBM/watson-discovery-food-reviews#69]
I am working on a project and I have a csv file which I want to convert the reviews present in the csv file to json, I have been able to do that and I have a large json file, but I was wondering how you broke your json file such that you have each reviews from 1-1000 well labelled

**Comment by stevemar** [comment]
A small bit of JavaScript was written to handle the conversation and splitting. We checked it in when we open sourced the code, check the tools folder:

https://github.com/IBM/watson-discovery-food-reviews/blob/master/tools/csvtojson.js

**Comment by Tkprudent** [comment]
@stevemar to get that done to my csv file, would I need to use javascript as well, because the file I am working with is a csv file having  productid, productname and reviews,

**Comment by Tkprudent** [comment]
`const csvFilePath='C:/Users/KazeemTijani/Desktop/mainTPS.csv';
const csv=require('csvtojson');
const fs=require('fs');

// Filters
let everyNth = 10;  // Keep every Nth row
let rowLimit = 2000;  // Max number of rows to parse
let padding = '000';  // to Line up the numbers and slice(-4).
let fileLimit = 2000;  // Max number of files to write

let files = 0;
let lines = -1;

csv({
  headers:['surveyId','ProductCode','ltrScore','comments'],
  noheader:false,
  colParser:{
    'ltrScore':'number',
  },
  checkType:false
})
  .fromFile(csvFilePath)
  .preFileLine((fileLineString, lineIdx)=>{
    lines += 1;
    if (rowLimit > 0 && lineIdx - 1 > rowLimit) {
      return '';
    } 
    if (everyNth > 0 && ((lines % everyNth) > 0)) {
      return '';
    }
    return fileLineString;
  })
  .on('Desktop',(jsonStr)=>{
    files += 1;
    if (files - 1  < fileLimit) {
      fs.writeFile('C:/Users/KazeemTijani/Desktop/offering_review/review_' + (padding + files).slice(-4) + '.json', jsonStr, (err) => {
        if (err) throw err;
        // console.log('The file has been saved!');
      });
    }
  })
  .on('done',(error)=>{
    if (error) throw error;
    // console.log('end');
  });`

**Comment by Tkprudent** [comment]
Kindly help check through that if it made any sense, its my first time using Javascript, But i need to get the json file to split, thanks

**Comment by rhagarty** [comment]
@Tkprudent - hello. If you aren't familiar with Javascript, this may not be the best code pattern for you to attempt. As for your changes to the script, one problem I see is you use `on('Desktop'`. This needs to be changed back to `on('data'`. Those are events being returned from the stream, and not file locations. I would recommend running the script and see what it does. Easy enough to delete bad files and try again as you work through any issues.

**Comment by Tkprudent** [comment]
Thanks Steve and Rich for taking time to help out
